### ISSUE TITLE
I am unclear on what exactly this is offering

### ISSUE THREAD

**Issue by CESlater** [xstevens/decoderbufs#4]
Greetings:

      I have a C++ application that uses Protobufs to manage it's data. I saw your work and believe it would do the following:

Storage
     1) use PBs bool SerializeToString(string* output) const; to produce a string
     2) use your tools to store said string into a Postgres DB

Loading
     1) use your tools to store retrieve a string from a Postgres DB
     2) use PBs bool bool ParseFromString(const string& data); to rebuild the model in memory

     Is this correct? Might you have an example?

    I also get the impression you might be able to access individual components of the PB while it remains inside the DB ( analogous to "shredding") .. is this a capability?

Regards
Carl

**Comment by xstevens** [comment]
@CESlater This plugin can't accept any incoming data. It's a logical decoding plugin. The plugin only gets called by Postgres internals when changes are made if a logical slot has been created.  For more info on logical decoding check out the [Postgres docs](http://www.postgresql.org/docs/current/static/logicaldecoding.html).

I'm not sure I see what the benefits or reasons would be to store Protobufs in the database as strings, but I think what you're describing would be doable with a custom Postgres plugin. Just not this one.
